מטלה2/BlogProject/BlogProject/Models/BlogFan.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace BlogProject.Models
{
    public class BlogFan
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public DateTime BirthDate { get; set; }
        public int Seniority { get; set; }
    }

    public class BlogFanDbContext: DbContext
    {
        public DbSet<BlogFan> FansClub { get; set; }
    }
}

מטלה2/BlogProject/BlogProject/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlogProject.Controllers
{
    public class BlogController : Controller
    {
        // GET: Blog
        public ActionResult Index()
        {
            return View();
        }
    }
}

מטלה2/BlogProject/BlogProject/Controllers/BlogFansController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BlogProject.Models;

namespace BlogProject.Controllers
{
    public class BlogFansController : Controller
    {
        private BlogFanDbContext db = new BlogFanDbContext();

        // GET: BlogFans
        public ActionResult Index()
        {
            return View(db.FansClub.ToList());
        }

        // GET: BlogFans/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogFan blogFan = db.FansClub.Find(id);
            if (blogFan == null)
            {
                return HttpNotFound();
            }
            return View(blogFan);
        }

        // GET: BlogFans/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: BlogFans/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,FirstName,LastName,Gender,BirthDate,Seniority")] BlogFan blogFan)
        {
            if (ModelState.IsValid)
            {
                db.FansClub.Add(blogFan);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(blogFan);
        }

        // GET: BlogFans/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogFan blogFan = db.FansClub.Find(id);
            if (blogFan == null)
            {
                return HttpNotFound();
            }
            return View(blogFan);
        }

        // POST: BlogFans/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,FirstName,LastName,Gender,BirthDate,Seniority")] BlogFan blogFan)
        {
            if (ModelState.IsValid)
            {
                db.Entry(blogFan).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(blogFan);
        }

        // GET: BlogFans/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogFan blogFan = db.FansClub.Find(id);
            if (blogFan == null)
            {
                return HttpNotFound();
            }
            return View(blogFan);
        }

        // POST: BlogFans/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BlogFan blogFan = db.FansClub.Find(id);
            db.FansClub.Remove(blogFan);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

מטלה2/BlogProject/BlogProject/Views/Blog/Index.cshtml
@{
    ViewBag.Title = "Blog";
}

@section UpperSection {
    <section id="searchContent">
        <!-- Search section -->
        <form>
            <!-- Search section form -->
            <h3>Search</h3>
            Date:
            <input type="date" name="postDate">
            Posted by:
            <input type="text" name="postedBy">
            E-mail:
            <input type="email" name="email">
            Comment content:
            <input type="text" name="commentContent">
            Minimal number of comments
            <input type="range" name="minComments" min="1" max="10">
            <input type="reset" value="Reset">
            <input type="submit" value="Search">
        </form>
    </section>
}

<section>
    <article class="blogPost">
        <header>
            <h2>This is the title of a blog post</h2>
            <p>Posted on <time datetime="2009-06-29T23:31+01:00">June 29th 2009</time> by <a href="#">Mads Kjaer</a> - <a href="#comments">3 comments</a></p>
        </header>
        <div>
            <p>Lorem ipsum dolor sit amet, tellus eu orci lacus blandit. Cras enim nibh, sodales ultricies elementum vel, fermentum id tellus. Proin metus odio, ultricies eu pharetra dictum, laoreet id odio. Curabitur in odio augue. Morbi congue auctor interdum. Phasellus sit amet metus justo. Phasellus vitae tellus orci, at elementum ipsum. In in quam eget diam adipiscing condimentum. Maecenas gravida diam vitae nisi convallis vulputate quis sit amet nibh. Nullam ut velit tortor. Curabitur ut elit id nisl volutpat consectetur ac ac lorem. Quisque non elit et elit lacinia lobortis nec a velit. Sed ac nisl sed enim consequat porttitor.</p>

            <img src="~/Content/images/flower.png" alt="Flower" />

            <p>Pellentesque ut sapien arcu, egestas mollis massa. Fusce lectus leo, fringilla at aliquet sit amet, volutpat non erat. Aenean molestie nibh vitae turpis venenatis vel accumsan nunc tincidunt. Suspendisse id purus vel felis auctor mattis non ac erat. Pellentesque sodales venenatis condimentum. Aliquam sit amet nibh nisi, ut pulvinar est. Sed ullamcorper nisi vel tortor volutpat eleifend. Vestibulum iaculis ullamcorper diam consectetur sagittis. Quisque vitae mauris ut elit semper condimentum varius nec nisl. Nulla tempus porttitor dolor ac eleifend. Proin vitae purus lectus, a hendrerit ipsum. Aliquam mattis lacinia risus in blandit.</p>
            <video controls="controls">
                <source src="~/Content/images/shauli.mp4" type="video/mp4" />
                Your browser does not support the video tag.
            </video>
            <p>Vivamus vitae nulla dolor. Suspendisse eu lacinia justo. Vestibulum a felis ante, non aliquam leo. Aliquam eleifend, est viverra semper luctus, metus purus commodo elit, a elementum nisi lectus vel magna. Praesent faucibus leo sit amet arcu vehicula sed facilisis eros aliquet. Etiam sodales, enim sit amet mollis vestibulum, ipsum sapien accumsan lectus, eget ultricies arcu velit ut diam. Aenean fermentum luctus nulla, eu malesuada urna consequat in. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque massa lacus, sodales id facilisis ac, lobortis sed arcu. Donec hendrerit fringilla ligula, ac rutrum nulla bibendum id. Cras sapien ligula, tincidunt eget euismod nec, ultricies eu augue. Nulla vitae velit sollicitudin magna mattis eleifend. Nam enim justo, vulputate vitae pretium ac, rutrum at turpis. Aenean id magna neque. Sed rhoncus aliquet viverra.</p>
        </div>
    </article>
</section>
<section id="comments">
    <h3>Comments</h3>
    <article>
        <header>
            <a href="#">George Washington</a> on <time datetime="2009-06-29T23:35:20+01:00">June 29th 2009 at 23:35</time>
        </header>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut.</p>
    </article>
    <article>
        <header>
            <a href="#">Benjamin Franklin</a> on <time datetime="2009-06-29T23:40:09+01:00">June 29th 2009 at 23:40</time>
        </header>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut.</p>
    </article>
    <article>
        <header>
            <a href="#">Barack Obama</a> on <time datetime="2009-06-29T23:59:00+01:00">June 29th 2009 at 23:59</time>
        </header>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut.</p>
    </article>


</section>
<form action="#" method="post">
    <h3>Post a comment</h3>
    <p>
        <label for="name">Name</label>
        <input name="name" id="name" type="text" required />
    </p>
    <p>
        <label for="email">E-mail</label>
        <input name="email" id="email" type="email" required />
    </p>
    <p>
        <label for="website">Website</label>
        <input name="website" id="website" type="url" />
    </p>
    <p>
        <label for="comment">Comment</label>
        <textarea name="comment" id="comment" required></textarea>
    </p>
    <p><input type="submit" value="Post comment" /></p>
</form>

מטלה2/BlogProject/BlogProject/Views/BlogFans/Create.cshtml
@model BlogProject.Models.BlogFan

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="fanCreateEdit form-horizontal">
        <h4>BlogFan</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BirthDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BirthDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BirthDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Seniority, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Seniority, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Seniority, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div class="blogButton">
    @Html.ActionLink("Back to List", "Index")
</div>

מטלה2/BlogProject/BlogProject/Views/BlogFans/Delete.cshtml
@model BlogProject.Models.BlogFan

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BlogFan</h4>
    <hr />
    <dl class="fansDetailsDelete dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BirthDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Seniority)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Seniority)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="blogButton deleteFanButtons form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

מטלה2/BlogProject/BlogProject/Views/BlogFans/Details.cshtml
@model BlogProject.Models.BlogFan

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>BlogFan</h4>
    <hr />
    <dl class="fansDetailsDelete dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BirthDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Seniority)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Seniority)
        </dd>

    </dl>
</div>
<p class="blogButton">
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

מטלה2/BlogProject/BlogProject/Views/BlogFans/Edit.cshtml
@model BlogProject.Models.BlogFan

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="fanCreateEdit form-horizontal">
        <h4>BlogFan</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BirthDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BirthDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BirthDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Seniority, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Seniority, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Seniority, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div class="blogButton">
    @Html.ActionLink("Back to List", "Index")
</div>

מטלה2/BlogProject/BlogProject/Views/BlogFans/Index.cshtml
@model IEnumerable<BlogProject.Models.BlogFan>

@{
    ViewBag.Title = "FanClub";
}

<h2>Index</h2>

<p class="blogButton">
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BirthDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Seniority)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Gender)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BirthDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Seniority)
        </td>
        <td class="blogButton">
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

מטלה2/BlogProject/BlogProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <!-- <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />-->
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <!-- Background audio - without controls -->
    <audio id="BGAudio" autoplay>
        <source src="~/Content/audio/audio.ogg" type="audio/ogg">
        <source src="~/Content/audio/audio.mp3" type="audio/mpeg">
        Your browser does not support the audio tag.
    </audio>

    <header>
        <h1>Ha-Blog Shel Shauli 1</h1>
    </header>

    <nav>
        <!-- Navigation -->
        <ul>
            <li class="@(ViewBag.Title == "Blog" ? "selected" : "")">@Html.ActionLink("Blog", "Index", "Blog")</li>
            <li><a href="#">About</a></li>
            <li class="@(ViewBag.Title == "FanClub" ? "selected" : "")">@Html.ActionLink("Fan Club", "Index", "BlogFans")</li>
            <li><a href="#">Contact</a></li>
            <li class="subscribe">
                <a href="#">
                    <div id="transDemo2">
                        <div class="hover">
                            <img src=http://www.ashlylorenzana.com/wp-content/uploads/2013/12/12065637851779660844SRD_RSS_Logo.svg_.hi_.png width="30" height="30">
                        </div>
                        Subscribe via. RSS
                    </div>
                </a>
            </li>
        </ul>
    </nav>
    <section id="intro">
        <!-- Introduction -->
        <header>
            <h2>Do you have questions for me?</h2>
        </header>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut.</p>
        <img src="~/Content/images/intro_shauli.png" alt="Shauli" />
    </section>

    <div id="upperSection">
        @RenderSection("UpperSection", required: false)
    </div>

    <div id="content">
        <div id="mainContent">
            @RenderBody()
        </div>
        <aside>
            <section>
                <header>
                    <h3>Categories</h3>
                </header>
                <ul>
                    <li><a href="#">Lorem ipsum dolor</a></li>
                    <li><a href="#">Sit amet consectetur</a></li>
                    <li><a href="#">Adipisicing elit sed</a></li>
                </ul>
            </section>
            <section>
                <header>
                    <h3>Archives</h3>
                </header>
                <ul>
                    <li><a href="#">December 2008</a></li>
                    <li><a href="#">January 2009</a></li>
                    <li><a href="#">February 2009</a></li>
                    <li><a href="#">March 2009</a></li>
                </ul>
            </section>
        </aside>
    </div>

    <div>
        <footer>
            <!-- Footer -->
            <div>
                <section id="about">
                    <header>
                        <h3>About</h3>
                    </header>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut la</p>
                </section>
                <section id="blogroll">
                    <header>
                        <h3>Blogroll</h3>
                    </header>
                    <ul>
                        <li><a href="#">NETTUTS+</a></li>
                        <li><a href="#">FreelanceSwitch</a></li>
                    </ul>
                </section>
                <section id="popular">
                    <header>
                        <h3>Popular</h3>
                    </header>
                    <ul>
                        <li><a href="#">This is the title of a blog post</a></li>
                        <li><a href="#">Lorem ipsum dolor sit amet</a></li>
                        <li><a href="#">Consectetur adipisicing elit, sed do eiusmod</a></li>
                    </ul>
                </section>
            </div>
        </footer>
    </div>

    <!--
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">

        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div> -->

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <!--<script src="~/Scripts/bootstrap.min.js"></script>-->
</body>
</html>